### ISSUE TITLE
Websites with svg files cannot render using Jazz services

### ISSUE THREAD

**Issue by suryajak** [tmobile/jazz#33]
### Description

Websites with svg files cannot render using Jazz services

### Steps to Reproduce

1. Create a Jazz service with the website template
2. Clone the repo
3. Add a svg file and reference it in your html
4. Push code and once the website is deployed check for the page with svg.

**Expected behavior:** 
Page renders the image

**Actual behavior:** 
Missing image icon rendered by browser

**Reproduces how often:** 
100%

**Comment by chimpuz** [comment]
Fixed with PR: https://github.com/tmobile/jazz/pull/116

Needs testing though.

**Comment by suryajak** [comment]
Fixed as part of [v1.4](https://github.com/tmobile/jazz/releases/tag/v1.4) release
