### ISSUE TITLE
Feature request - Configure Lambda authorizer for an api

### ISSUE THREAD

**Issue by jiettu** [tmobile/jazz#429]
### Description

Please provide a way to attach Lambda authorizer for an api. Maybe in deployment-env.yml or swagger.json. If we attach authorizer manually to an api then it gets removed every time when we do a new deployment for that api.
Please guide me to documentation if this feature already exists.

**Comment by suryajak** [comment]
This feature already exists. I just added documentation, so please refer here: https://github.com/tmobile/jazz/wiki/How-To
