### ISSUE TITLE
New user login shows user doesn't exist

### ISSUE THREAD

**Issue by DaemonWill** [tmobile/jazz#45]
### Description

Upon registering for a new account and verifying the email, the new user is unable to login to the app and an alert shows that the user does not exist. Login is most likely case-sensitive and only accepting emails in all lowercase, a user entering credentials any other way will encounter this issue.

### Steps to Reproduce

1. Reigster for a new account
2. Click on the email confirmation link when the email is received in your inbox
3. After verification, attempt to login to the app and alter the case : 
     ex: registered name = ("daymanStarChild@test.com", "dayManStarchild@Test.com") but the only accepted name upon login is probably ("daymanstarchild@test.com")

**Expected behavior:** [What you expect to happen]
The user should be forwarded to services portal after successful login

**Actual behavior:** [What actually happens]
If username isn't in all lower case, the user is rejected and popup states user doesn't exist

**Comment by suryajak** [comment]
This has been fixed with release v1.4.x+
