### ISSUE TITLE
logic for is-service-available shows service doesn't exist if service_name isn't all lowercase

### ISSUE THREAD

**Issue by DaemonWill** [tmobile/jazz#48]
### Description

When checking dev/platform/is-service-available for an existing service with proper domain and service_name credentials; the output will indicate service doesn't exist if the service_name isn't all lowercase.

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

Aha! Link: https://t-mobile1t-mobile.aha.io/features/JZ-33

**Comment by devsatishm** [comment]
This is fixed now!
