### ISSUE TITLE
Migration from one AWS Instance to another AWS instance 

### ISSUE THREAD

**Issue by ramumoonraft** [tmobile/jazz#487]
we are bean using the JAZZ to build our services for a long time and we have successfully created more than 30 services till now which are working great.
we have installed it on  **AWS instance ( I1 )** and now we would like to migrate this to a different **Instance ( I2 )**  of another AWS account.

Can we migrate all the 30 plus services without recreating them or using the existing repositories?

Aha! Link: https://t-mobile1t-mobile.aha.io/features/JZ-14

**Comment by suryajak** [comment]
We currently don't have an out-of-box option to migrate from **AWS instance ( I1 )**  to **AWS instance ( I2 )** . Having said that, we can automate large parts of it without you having to create 30 of them through the UI in the new instance.  To get more help on this, can you connect to us via [slack](https://github.com/tmobile/jazz#try-jazz)?

**Comment by suryajak** [comment]
@ramumoonraft: Closing this issue as we haven't heard back from you. If you still need help, let us know and we will be more than happy to explore this further.
