### ISSUE TITLE
Admin is able to see all user services by default

### ISSUE THREAD

**Issue by suryajak** [tmobile/jazz#50]
### Description

During install, admin user is created by default. When new users register and create their services, the admin dashboard now shows all other user services.

### Steps to Reproduce

1. Register a new user
2. Create a new service using the new user account
3. Login using the admin user. Dashboard now shows the new user service

**Expected behavior:** 
Admin dashboard shouldn't show other user services

**Actual behavior:** 
Admin dashboard shows other user services

**Reproduces how often:** 
100%

**Comment by DaemonWill** [comment]
Issue is being addressed with possible fixes in [Pull Request 57](https://github.com/tmobile/jazz/pull/57) .
