### ISSUE TITLE
Jazz shouldn't need to be installed in the same AWS account where User services are to be deployed 

### ISSUE THREAD

**Issue by deepusundar** [tmobile/jazz#628]
### Description
This sounds like a limitation that Jazz should be installed in the same account where the User services should be eventually deployed. It would be nice if the deployment target (The account where the User Services are deployed) is a configurable and Jazz allows deployment to a different account, not necessarily the same account.

**Comment by bleggett** [comment]
Updated the title to better reflect what I think you're asking about.

We discussed this internally some weeks back I believe, as a security consideration.

**Comment by deepusundar** [comment]
I was thinking from a perceptive of leveraging Jazz for a different client. Since Jazz being a developer tool, is it ideal the Client pays the bill of maintaining the development infrastructure?  Another case would be, if we want to do a multi-account strategy wherein I want to maintain the production environment in a different account for various reasons, this would become a limitation.

**Comment by deepusundar** [comment]
> Updated the title to better reflect what I think you're asking about.
> 
> We discussed this internally some weeks back I believe, as a security consideration.

Cool. We can think of a few security concerns due to Multi-tenancy and also having all the environments (dev, stg, prod) on the same account.  Not sure if Clients would prefer that deployment model.

**Comment by devsatishm** [comment]
@deepusundar Requirements makes sense. Multi-account/Multi-region support should in-turn solve this. Jazz admin can tweak the stack configurations to control where user services should be deployed to (same/different accounts OR different account per environment and so on).

**Comment by suryajak** [comment]
> I was thinking from a perceptive of leveraging Jazz for a different client. Since Jazz being a developer tool, is it ideal the Client pays the bill of maintaining the development infrastructure? Another case would be, if we want to do a multi-account strategy wherein the Client want to maintain the production environment in a different account for various reasons, this would become a limitation.

@deepusundar: Perhaps this [feature](https://github.com/tmobile/jazz/projects/5) is what you are looking for?

**Comment by deepusundar** [comment]
@suryajak Look like the multi-account feature would solve this issue technically. However, if not already taken care it would be nice to make this as one of the visible high-level jazz feature - meaning the deployment target configuration should be made explicit and driven all the way from installer.  It’s ok to be defaulted to the same account but should be based on user input.

**Comment by devsatishm** [comment]
Hey @deepusundar, our latest [release](https://github.com/tmobile/jazz/releases/tag/v1.16) should cover these requirements. Give it a try.
