### ISSUE TITLE
Jazz Logs Module need a cheaper back-end alternative

### ISSUE THREAD

**Issue by deepusundar** [tmobile/jazz#641]
### Description
Current implementation of logs feature using Elastic Search managed service is apparently very expensive. Found that just 5 days of Jazz usage bumped up the cost to 5+K INR and the Elastic Search instance itself took more than 65% of the total costs. 

Need a smarter and cost-effective solution for Logs feature as this can become a showstopper.

**Comment by suryajak** [comment]
@deepusundar: ES is certainly expensive relative to all the other components that Jazz installs and uses. Is your comment about an alternate "smarter and cost-effective solution for Logs" specifically for folks who are evaluating Jazz? For folks who run Jazz for their production use cases, I would imagine the cost of ES is similar (or smaller) compared to any other solution out there.

**Comment by deepusundar** [comment]
@suryajak That's a good news.  But it would be nice to pull some statistics from the Jazz internal installation and validate the figures.  From our experience, the ES cost is shooting up fast and which amounts to around 65% of the total costs. Of course these stats are from a Jazz evaluation instance.

**Comment by devsatishm** [comment]
@deepusundar This is available as part of one of the [releases](https://github.com/tmobile/jazz/releases/tag/v1.18.1) last year. Please check the release notes and any feedback is welcome!
