### ISSUE TITLE
Feature Request: Framework option (Basic, React & Angular) while creating and deploying a new website service.

### ISSUE THREAD

**Issue by francis-ve** [tmobile/jazz#821]
### Description

Multiple framework support to create website service through Jazz UI

**Current behavior:**

Currently Jazz supports creating a basic web site. Users then have to configure their "service repository" to deploy a Angular/ReactJS app.

**Expected behavior:**

We want to make the current "create website" option similar to our API/Function option. In this case users would choose "create website" option and they will a "framework" option to choose from a) Angular b) Basic c) React. Based on the user selection, the appropriate template will be chosen where it is preconfigured with the best practices template for the framework.

**Comment by devsatishm** [comment]
This is now available as part of release [v1.15.1](https://github.com/tmobile/jazz/releases/tag/v1.15.1)!
