### ISSUE TITLE
In gitlab UI, the repo clone URL for services are configured on an internal DNS 

### ISSUE THREAD

**Issue by deepusundar** [tmobile/jazz#825]
### Description

Service Clone URL is based on internal DNS in GitLab UI. For example: http://ip-172-xx-xxx-183.ec2.internal/cas/demo_test.git. The URL seems to be not working outside since being internal. 

### Steps to Reproduce

After Jazz installation, create a new service through UI.  Once the service is created successfully, click on link 'Git Repo' from service detail page and navigate to GitLab UI and check the clone URL.  

Suggestions:
Use the same DNS as GitLab instance instead of an internal IP based DNS for fork/clone URL.  Also add a copy button functionality for clone URL next to 'Git Repo' link in the Jazz UI - a minor usability improvement (of course we can copy the Web link and add a '.git' extension to get the clone URL)

**Comment by suryajak** [comment]
@pspani can you take a look?

**Comment by pspani** [comment]
Thanks @deepusundar for logging the issue. 

I was unable to reproduce the issue. In my instance, the gitlab is hosted on http://18.xxx.xxx.xxx and the clone url was http://18.xxx.xxx.xxx/cas/jazztest_servicename669248989.git. The url was accessible and I was able to clone the repo. 

@deepusundar If possible can you give me more detailed steps on how to reproduce the issue.

**Comment by suryajak** [comment]
@pspani: The issue can be repro-ed in our training env.

**Comment by rajeevr2715** [comment]
@suryajak @deepusundar This has been changed since we moved the docker into ECS fargate. Created one PR https://github.com/tmobile/jazz-installer/pull/482 to reflect the exact URL (Application Load balancer) instead of internal ecs ip.
