### ISSUE TITLE
Python3.6 template error: AttributeError on 'exception_message = e.message'

### ISSUE THREAD

**Issue by deepusundar** [tmobile/jazz#837]
### Description
Python template 3.6 is not compatible with 3.6 run time. Look like the template is not tested for exception conditions. Python 3.x exception handling has been changed from 2.x version.   

### Steps to Reproduce
Raise an exception in the try block. The code fails with an 'AttributeError' on  e.message

**Comment by pspani** [comment]
thanks @deepusundar for reporting this issue. This issue has been fixed by the team :)
