### ISSUE TITLE
User email validation during login needs update 

### ISSUE THREAD

**Issue by suryajak** [tmobile/jazz#89]
Have you read Jazz's Code of Conduct? By filing an Issue, you are expected to comply with it, including treating everyone with respect: https://github.com/tmobile/jazz/blob/master/CODE_OF_CONDUCT.md

Do you want to ask a question? Are you looking for support? Connect with us on [Slack](https://github.com/tmobile/jazz/blob/master/CONTRIBUTING.md#join-the-tmobile-slack-team) to get help.

### Description

User email validation during login seems to fail when the email address has an upper case character.

### Steps to Reproduce

1. Launch the Jazz UI and click on login button
2. Use a upper case letter in a valid user email address

**Expected behavior:** Client side validation for email address should pass

**Actual behavior:** User sees an error "Please enter a valid email"

**Reproduces how often:** 100%

### Additional Information

Can you reprodue this issue on our [demo site](https://github.com/tmobile/jazz/blob/master/CONTRIBUTING.md#try-it-out)? If you can, please share your service as well as namespace to help us quickly troubleshoot the issue.

Aha! Link: https://t-mobile1t-mobile.aha.io/features/JZ-30

**Comment by gokulpits** [comment]
There is no email validation issue for the uppercase in the latest master branch pull

**Comment by gokulpits** [comment]
The isssue existing in the login time is that there is no validation for password field

**Comment by suryajak** [comment]
Thanks for taking a look at it. It was fixed with v1.7, closing it now.
